networks:
  proxy:
    name: goat

services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      proxy:

  redis:
    image: redis:7.4.1-alpine
    networks:
      proxy:

  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: goat
      POSTGRES_USER: goat
      POSTGRES_PASSWORD: goat
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      proxy:

  geoapi:
    image: ghcr.io/plan4better/goat/geoapi:latest
    networks:
      proxy:

volumes:
  postgres-data:
