"""add display_name and category in uploaded_assets table

Revision ID: 642c72ecdf4a
Revises: 5bdac5cb32ff
Create Date: 2025-09-10 16:21:00.778430

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  



# revision identifiers, used by Alembic.
revision = '642c72ecdf4a'
down_revision = '5bdac5cb32ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_asset', sa.Column('display_name', sa.String(length=255), nullable=True), schema='customer')
    op.add_column('uploaded_asset', sa.Column('category', sa.String(length=100), nullable=True), schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_asset', 'category', schema='customer')
    op.drop_column('uploaded_asset', 'display_name', schema='customer')
    # ### end Alembic commands ###
